AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Redash Screenshot Bot for Slack using Puppeteer

Parameters:
  Env:
    Type: String
    AllowedValues:
      - development
      - staging
      - production
  FontconfigPath:
    Type: String
  RedashApiKey:
    Type: String
  RedashHost:
    Type: String
  SlackBotToken:
    Type: String
  SlackSigningSecret:
    Type: String
  LambdaSecurityGroupId:
    Type: String
  LambdaPublicSubnetId:
    Type: String

Conditions:
  IsNotDevelopment: !Not
    - !Equals
      - !Ref Env
      - development

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs22.x
    MemorySize: 1024
    Environment:
      Variables:
        NODE_PATH: ./:/opt/nodejs/node_modules
        ENV: !Ref Env
        FONTCONFIG_PATH: !Ref FontconfigPath
        REDASH_API_KEY: !Ref RedashApiKey
        REDASH_HOST: !Ref RedashHost
        SLACK_BOT_TOKEN: !Ref SlackBotToken
        SLACK_SIGNING_SECRET: !Ref SlackSigningSecret

Resources:
  RedashBotApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env
      OpenApiVersion: 3.0.2

  RedashBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      CodeUri: ./src/handlers
      Architectures:
        - x86_64
      Layers:
        - !Ref DependenciesLayer
      Events:
        SlackEvents:
          Type: Api
          Properties:
            Path: /slack/events
            Method: post
            RestApiId: !Ref RedashBotApi
      VpcConfig: !If
        - IsNotDevelopment
        - SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
          SubnetIds:
            - !Ref LambdaPublicSubnetId
        - !Ref AWS::NoValue
      RuntimeManagementConfig:
        UpdateRuntimeOn: FunctionUpdate

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./layers/dependencies/nodejs
      CompatibleRuntimes:
        - nodejs22.x
      CompatibleArchitectures:
        - x86_64
      Description: Layer for Dependencies
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs22.x

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${RedashBotFunction}"
      RetentionInDays: 14
